import type {
  Company,
  Job,
  Candidate,
  Application,
  PipelineColumn,
  Analytics,
  Conversation,
  PricingPlan,
} from './types'

export const companies: Company[] = [
  {
    id: 'c1',
    name: 'Stripe',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=stripe&backgroundColor=6772e5',
    industry: 'FinTech',
    size: '1,000–5,000',
    location: 'San Francisco, CA',
    website: 'stripe.com',
    description: 'Financial infrastructure for the internet.',
    culture: ['Innovation', 'User-Centric', 'High Performance', 'Transparency'],
    benefits: ['Equity', 'Remote', 'Top Health', '401K Match', 'Learning Budget'],
    rating: 4.8,
    reviewCount: 2341,
    verified: true,
    plan: 'enterprise',
  },
  {
    id: 'c2',
    name: 'Notion',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=notion&backgroundColor=2eaadc',
    industry: 'Productivity SaaS',
    size: '500–1,000',
    location: 'New York, NY',
    website: 'notion.so',
    description: 'The connected workspace where better, faster work happens.',
    culture: ['Creativity', 'Collaboration', 'Autonomy', 'Diversity'],
    benefits: ['Remote-First', 'Equity', 'Unlimited PTO', 'Wellness', 'Equipment Budget'],
    rating: 4.7,
    reviewCount: 1204,
    verified: true,
    plan: 'growth',
  },
  {
    id: 'c3',
    name: 'Vercel',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=vercel&backgroundColor=000000',
    industry: 'Developer Tools',
    size: '200–500',
    location: 'Remote',
    website: 'vercel.com',
    description: 'Build and deploy the best web experiences with the frontend cloud.',
    culture: ['Open Source', 'Developer First', 'Speed', 'Excellence'],
    benefits: ['Fully Remote', 'Equity', 'Top-of-Market Salary', 'Conference Budget'],
    rating: 4.9,
    reviewCount: 876,
    verified: true,
    plan: 'enterprise',
  },
  {
    id: 'c4',
    name: 'Linear',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=linear&backgroundColor=5e6ad2',
    industry: 'Project Management',
    size: '50–200',
    location: 'San Francisco, CA',
    website: 'linear.app',
    description: 'The issue tracking tool you\'ll enjoy using.',
    culture: ['Craftsmanship', 'Speed', 'Simplicity', 'Opinionated'],
    benefits: ['Equity', 'Remote', 'High Autonomy', 'Top Salary'],
    rating: 4.9,
    reviewCount: 412,
    verified: true,
    plan: 'growth',
  },
  {
    id: 'c5',
    name: 'Figma',
    logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=figma&backgroundColor=f24e1e',
    industry: 'Design Tools',
    size: '1,000–5,000',
    location: 'San Francisco, CA',
    website: 'figma.com',
    description: 'Where teams design together.',
    culture: ['Design-Centric', 'Collaboration', 'Inclusivity', 'Innovation'],
    benefits: ['Equity', 'Remote Options', 'Great Benefits', '401K'],
    rating: 4.7,
    reviewCount: 1876,
    verified: true,
    plan: 'enterprise',
  },
]

export const jobs: Job[] = [
  {
    id: 'j1',
    companyId: 'c1',
    company: companies[0],
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    type: 'full-time',
    workMode: 'hybrid',
    level: 'senior',
    location: 'San Francisco, CA',
    salaryMin: 180000,
    salaryMax: 240000,
    currency: 'USD',
    description: 'We\'re looking for a Senior Frontend Engineer to join our Dashboard team and help build the best financial tools for businesses worldwide. You\'ll work on high-impact products used by millions.',
    requirements: [
      '5+ years of experience with React and TypeScript',
      'Deep understanding of web performance optimization',
      'Experience with state management (Redux, Zustand, Jotai)',
      'Strong understanding of CSS and design systems',
      'Experience shipping features in a fast-paced environment',
    ],
    niceToHave: [
      'Experience with WebGL or Canvas',
      'Contributions to open source',
      'GraphQL experience',
    ],
    skills: ['React', 'TypeScript', 'CSS', 'GraphQL', 'Next.js', 'Performance'],
    benefits: ['Equity', 'Remote Options', 'Top Health', '$1K Equipment', 'Learning Budget'],
    postedAt: '2025-04-20',
    expiresAt: '2025-05-20',
    applicantCount: 284,
    viewCount: 4230,
    status: 'active',
    featured: true,
  },
  {
    id: 'j2',
    companyId: 'c2',
    company: companies[1],
    title: 'Product Manager, Growth',
    department: 'Product',
    type: 'full-time',
    workMode: 'remote',
    level: 'mid',
    location: 'Remote',
    salaryMin: 140000,
    salaryMax: 190000,
    currency: 'USD',
    description: 'Join Notion\'s Growth team to drive user acquisition, activation, and retention at scale. You\'ll own key metrics and work closely with engineering, design, and data teams.',
    requirements: [
      '3+ years of product management experience',
      'Experience with growth metrics and A/B testing',
      'Strong analytical skills with SQL proficiency',
      'Excellent written and verbal communication',
    ],
    niceToHave: [
      'Experience at a PLG company',
      'Background in consumer or B2B SaaS',
    ],
    skills: ['Product Strategy', 'A/B Testing', 'SQL', 'Analytics', 'Growth', 'Roadmapping'],
    benefits: ['Remote', 'Equity', 'Unlimited PTO', 'Wellness Budget', 'Equipment'],
    postedAt: '2025-04-22',
    expiresAt: '2025-05-22',
    applicantCount: 412,
    viewCount: 6800,
    status: 'active',
    featured: true,
  },
  {
    id: 'j3',
    companyId: 'c3',
    company: companies[2],
    title: 'Staff Software Engineer',
    department: 'Infrastructure',
    type: 'full-time',
    workMode: 'remote',
    level: 'lead',
    location: 'Remote',
    salaryMin: 220000,
    salaryMax: 300000,
    currency: 'USD',
    description: 'As a Staff Engineer on our Infrastructure team, you\'ll architect the systems that power the frontend cloud — helping millions of developers deploy at the edge.',
    requirements: [
      '8+ years of software engineering experience',
      'Deep expertise in distributed systems',
      'Experience with edge computing or CDN infrastructure',
      'Strong background in Node.js and Go',
      'Proven track record of leading technical initiatives',
    ],
    niceToHave: [
      'Experience with Rust',
      'Open source contributions',
      'Publications or conference talks',
    ],
    skills: ['Go', 'Rust', 'Node.js', 'Distributed Systems', 'Edge Computing', 'Kubernetes'],
    benefits: ['Fully Remote', 'Top-of-Market Salary', 'Equity', 'Conference Budget'],
    postedAt: '2025-04-18',
    expiresAt: '2025-05-18',
    applicantCount: 156,
    viewCount: 3200,
    status: 'active',
    featured: false,
  },
  {
    id: 'j4',
    companyId: 'c4',
    company: companies[3],
    title: 'Product Designer',
    department: 'Design',
    type: 'full-time',
    workMode: 'hybrid',
    level: 'mid',
    location: 'San Francisco, CA',
    salaryMin: 160000,
    salaryMax: 210000,
    currency: 'USD',
    description: 'We\'re crafting a new standard for project management software. As a Product Designer at Linear, you\'ll shape the visual language and interaction patterns of our core product.',
    requirements: [
      '4+ years of product design experience',
      'Strong portfolio demonstrating systems thinking',
      'Proficiency in Figma',
      'Experience designing complex data-dense interfaces',
    ],
    niceToHave: [
      'Motion design skills',
      'Experience with design tokens',
      'B2B SaaS background',
    ],
    skills: ['Figma', 'Interaction Design', 'Design Systems', 'User Research', 'Prototyping'],
    benefits: ['Equity', 'Remote Flexibility', 'High Autonomy', 'Top Compensation'],
    postedAt: '2025-04-25',
    expiresAt: '2025-05-25',
    applicantCount: 320,
    viewCount: 5400,
    status: 'active',
    featured: true,
  },
  {
    id: 'j5',
    companyId: 'c5',
    company: companies[4],
    title: 'ML Engineer, Search & Recommendations',
    department: 'AI/ML',
    type: 'full-time',
    workMode: 'hybrid',
    level: 'senior',
    location: 'San Francisco, CA',
    salaryMin: 200000,
    salaryMax: 280000,
    currency: 'USD',
    description: 'Build the intelligence layer that helps millions of designers discover the right templates, components, and inspiration at the right moment.',
    requirements: [
      '5+ years of ML engineering experience',
      'Strong background in NLP and recommendation systems',
      'Proficiency in Python and PyTorch',
      'Experience deploying models to production at scale',
    ],
    niceToHave: [
      'Experience with vector databases',
      'Knowledge of transformer architectures',
      'Contributions to ML open source',
    ],
    skills: ['Python', 'PyTorch', 'NLP', 'Vector Search', 'Recommendations', 'MLOps'],
    benefits: ['Equity', 'Remote Options', 'Great Benefits', '401K'],
    postedAt: '2025-04-19',
    expiresAt: '2025-05-19',
    applicantCount: 198,
    viewCount: 4100,
    status: 'active',
    featured: false,
  },
  {
    id: 'j6',
    companyId: 'c1',
    company: companies[0],
    title: 'Engineering Manager, Payments',
    department: 'Engineering',
    type: 'full-time',
    workMode: 'hybrid',
    level: 'lead',
    location: 'New York, NY',
    salaryMin: 230000,
    salaryMax: 320000,
    currency: 'USD',
    description: 'Lead a team of 8-10 engineers building the core payments infrastructure that processes billions of dollars annually.',
    requirements: [
      '3+ years of engineering management experience',
      '7+ years of software engineering experience',
      'Experience managing distributed teams',
      'Strong background in fintech or payments',
    ],
    niceToHave: [
      'Experience scaling teams 2x+',
      'Background in compliance/risk systems',
    ],
    skills: ['Engineering Management', 'Payments', 'System Design', 'Team Building', 'Strategy'],
    benefits: ['Equity', 'Hybrid', 'Top Health', '401K Match', 'Management Coaching'],
    postedAt: '2025-04-21',
    expiresAt: '2025-05-21',
    applicantCount: 89,
    viewCount: 2800,
    status: 'active',
    featured: false,
  },
]

export const candidates: Candidate[] = [
  {
    id: 'can1',
    name: 'Alex Chen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    title: 'Senior Frontend Engineer',
    location: 'San Francisco, CA',
    email: 'alex.chen@email.com',
    phone: '+1 (415) 555-0101',
    bio: 'Passionate about building exceptional web experiences. 6 years crafting high-performance React applications at scale. Open to hybrid roles at companies with strong engineering culture.',
    skills: [
      { name: 'React', level: 'expert', verified: true, score: 96 },
      { name: 'TypeScript', level: 'expert', verified: true, score: 94 },
      { name: 'Next.js', level: 'advanced', verified: true, score: 90 },
      { name: 'GraphQL', level: 'advanced', verified: false },
      { name: 'CSS/Tailwind', level: 'expert', verified: true, score: 92 },
      { name: 'Performance', level: 'advanced', verified: false },
    ],
    experience: [
      {
        id: 'e1',
        company: 'Airbnb',
        title: 'Senior Frontend Engineer',
        startDate: '2022-01',
        current: true,
        description: 'Led frontend architecture for the Host Dashboard, improving performance by 40% and reducing bundle size by 30%.',
        skills: ['React', 'TypeScript', 'GraphQL', 'Performance'],
      },
      {
        id: 'e2',
        company: 'Dropbox',
        title: 'Frontend Engineer',
        startDate: '2019-06',
        endDate: '2022-01',
        current: false,
        description: 'Built reusable component library used by 50+ engineers across the organization.',
        skills: ['React', 'TypeScript', 'Design Systems'],
      },
    ],
    education: [
      {
        id: 'edu1',
        institution: 'UC Berkeley',
        degree: 'B.S.',
        field: 'Computer Science',
        startDate: '2015-09',
        endDate: '2019-05',
        gpa: 3.8,
      },
    ],
    matchScore: 96,
    salaryExpectation: 210000,
    availability: 'Open to opportunities',
    workPreference: ['hybrid', 'remote'],
    languages: ['English (Native)', 'Mandarin (Fluent)'],
    github: 'github.com/alexchen',
    linkedin: 'linkedin.com/in/alexchen',
    portfolio: 'alexchen.dev',
    assessmentScores: { javascript: 96, react: 94, typescript: 92 },
    verified: true,
    premium: true,
  },
  {
    id: 'can2',
    name: 'Priya Sharma',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    title: 'Product Manager',
    location: 'Remote (NYC-based)',
    email: 'priya.sharma@email.com',
    phone: '+1 (212) 555-0142',
    bio: 'Results-driven PM with 5 years in B2B SaaS. Obsessed with user insights and data-driven decision making. Looking for growth-stage companies with strong product culture.',
    skills: [
      { name: 'Product Strategy', level: 'expert', verified: true, score: 94 },
      { name: 'A/B Testing', level: 'advanced', verified: true, score: 89 },
      { name: 'SQL', level: 'intermediate', verified: true, score: 78 },
      { name: 'User Research', level: 'expert', verified: false },
      { name: 'Roadmapping', level: 'expert', verified: false },
    ],
    experience: [
      {
        id: 'e3',
        company: 'HubSpot',
        title: 'Senior Product Manager',
        startDate: '2021-03',
        current: true,
        description: 'Own the CRM mobile experience. Increased DAU by 35% through a full redesign initiative.',
        skills: ['Product Strategy', 'Mobile', 'Analytics'],
      },
    ],
    education: [
      {
        id: 'edu2',
        institution: 'Cornell University',
        degree: 'MBA',
        field: 'Technology Management',
        startDate: '2018-09',
        endDate: '2020-05',
      },
    ],
    matchScore: 91,
    salaryExpectation: 175000,
    availability: 'Available in 4 weeks',
    workPreference: ['remote'],
    languages: ['English (Native)', 'Hindi (Native)'],
    linkedin: 'linkedin.com/in/priyasharma',
    assessmentScores: { productStrategy: 94, analytics: 89 },
    verified: true,
    premium: false,
  },
  {
    id: 'can3',
    name: 'Marcus Johnson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    title: 'Staff Software Engineer',
    location: 'Austin, TX',
    email: 'marcus.j@email.com',
    phone: '+1 (512) 555-0183',
    bio: 'Infrastructure and distributed systems engineer with a track record of building systems at hyper-scale. Open to staff/principal roles at mission-driven companies.',
    skills: [
      { name: 'Go', level: 'expert', verified: true, score: 97 },
      { name: 'Kubernetes', level: 'expert', verified: true, score: 95 },
      { name: 'Distributed Systems', level: 'expert', verified: true, score: 96 },
      { name: 'Rust', level: 'advanced', verified: false },
      { name: 'Node.js', level: 'advanced', verified: true, score: 87 },
    ],
    experience: [
      {
        id: 'e4',
        company: 'Cloudflare',
        title: 'Staff Engineer',
        startDate: '2020-02',
        current: true,
        description: 'Architect of the edge routing layer handling 50M+ requests/second across 250 data centers.',
        skills: ['Go', 'Rust', 'Networking', 'Edge Computing'],
      },
    ],
    education: [
      {
        id: 'edu3',
        institution: 'Georgia Tech',
        degree: 'M.S.',
        field: 'Computer Science',
        startDate: '2016-09',
        endDate: '2018-05',
      },
    ],
    matchScore: 88,
    salaryExpectation: 270000,
    availability: 'Looking now',
    workPreference: ['remote'],
    languages: ['English (Native)'],
    github: 'github.com/mjohnson',
    linkedin: 'linkedin.com/in/marcusjohnson',
    assessmentScores: { go: 97, systems: 96, kubernetes: 95 },
    verified: true,
    premium: true,
  },
  {
    id: 'can4',
    name: 'Sofia Reyes',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sofia',
    title: 'Product Designer',
    location: 'Los Angeles, CA',
    email: 'sofia.reyes@email.com',
    phone: '+1 (323) 555-0211',
    bio: 'Senior product designer specializing in complex data-dense interfaces. Passionate about design systems and accessible design. Portfolio: sofiareyes.design',
    skills: [
      { name: 'Figma', level: 'expert', verified: true, score: 98 },
      { name: 'Design Systems', level: 'expert', verified: true, score: 95 },
      { name: 'User Research', level: 'advanced', verified: false },
      { name: 'Interaction Design', level: 'expert', verified: true, score: 93 },
      { name: 'Prototyping', level: 'expert', verified: false },
    ],
    experience: [
      {
        id: 'e5',
        company: 'Figma',
        title: 'Senior Product Designer',
        startDate: '2021-09',
        current: true,
        description: 'Led design for the Variables feature, used by 3M+ designers globally.',
        skills: ['Figma', 'Design Systems', 'Prototyping'],
      },
    ],
    education: [
      {
        id: 'edu4',
        institution: 'Rhode Island School of Design',
        degree: 'BFA',
        field: 'Graphic Design',
        startDate: '2015-09',
        endDate: '2019-05',
      },
    ],
    matchScore: 95,
    salaryExpectation: 190000,
    availability: 'Casually looking',
    workPreference: ['hybrid', 'onsite'],
    languages: ['English (Native)', 'Spanish (Native)'],
    linkedin: 'linkedin.com/in/sofiareyes',
    portfolio: 'sofiareyes.design',
    assessmentScores: { design: 98, figma: 95, systems: 93 },
    verified: true,
    premium: true,
  },
  {
    id: 'can5',
    name: 'Jordan Park',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordan',
    title: 'ML Engineer',
    location: 'Seattle, WA',
    email: 'jordan.park@email.com',
    phone: '+1 (206) 555-0167',
    bio: 'ML engineer specializing in NLP and recommendation systems. Previously at Amazon building product search. Looking for impactful AI-first companies.',
    skills: [
      { name: 'Python', level: 'expert', verified: true, score: 95 },
      { name: 'PyTorch', level: 'expert', verified: true, score: 93 },
      { name: 'NLP', level: 'advanced', verified: true, score: 91 },
      { name: 'MLOps', level: 'advanced', verified: false },
      { name: 'Vector Search', level: 'advanced', verified: true, score: 88 },
    ],
    experience: [
      {
        id: 'e6',
        company: 'Amazon',
        title: 'Applied Scientist',
        startDate: '2020-07',
        current: true,
        description: 'Built transformer-based ranking models for Amazon product search, improving relevance by 18%.',
        skills: ['Python', 'PyTorch', 'NLP', 'Ranking'],
      },
    ],
    education: [
      {
        id: 'edu5',
        institution: 'University of Washington',
        degree: 'M.S.',
        field: 'Machine Learning',
        startDate: '2018-09',
        endDate: '2020-05',
      },
    ],
    matchScore: 89,
    salaryExpectation: 240000,
    availability: 'Available now',
    workPreference: ['remote', 'hybrid'],
    languages: ['English (Fluent)', 'Korean (Native)'],
    github: 'github.com/jordanpark',
    linkedin: 'linkedin.com/in/jordanpark',
    assessmentScores: { python: 95, pytorch: 93, mlops: 88 },
    verified: true,
    premium: false,
  },
]

export const applications: Application[] = [
  {
    id: 'app1',
    jobId: 'j1',
    job: jobs[0],
    candidateId: 'can1',
    candidate: candidates[0],
    status: 'interview',
    appliedAt: '2025-04-21T09:30:00Z',
    updatedAt: '2025-04-24T14:00:00Z',
    matchScore: 96,
    stage: 'technical',
    rating: 5,
    notes: 'Exceptional React skills. Strong cultural fit. Schedule technical interview.',
  },
  {
    id: 'app2',
    jobId: 'j1',
    job: jobs[0],
    candidateId: 'can4',
    candidate: candidates[3],
    status: 'screening',
    appliedAt: '2025-04-22T11:00:00Z',
    updatedAt: '2025-04-22T11:00:00Z',
    matchScore: 72,
    stage: 'screening',
  },
  {
    id: 'app3',
    jobId: 'j2',
    job: jobs[1],
    candidateId: 'can2',
    candidate: candidates[1],
    status: 'interview',
    appliedAt: '2025-04-23T10:15:00Z',
    updatedAt: '2025-04-26T09:00:00Z',
    matchScore: 91,
    stage: 'phone_screen',
    rating: 4,
    notes: 'Great background. Solid growth metrics experience.',
  },
  {
    id: 'app4',
    jobId: 'j3',
    job: jobs[2],
    candidateId: 'can3',
    candidate: candidates[2],
    status: 'offer',
    appliedAt: '2025-04-19T08:00:00Z',
    updatedAt: '2025-04-27T16:00:00Z',
    matchScore: 88,
    stage: 'offer',
    rating: 5,
    notes: 'Outstanding systems background. Extending offer.',
  },
  {
    id: 'app5',
    jobId: 'j5',
    job: jobs[4],
    candidateId: 'can5',
    candidate: candidates[4],
    status: 'screening',
    appliedAt: '2025-04-24T13:00:00Z',
    updatedAt: '2025-04-24T13:00:00Z',
    matchScore: 89,
    stage: 'new',
  },
]

export const pipelineColumns: PipelineColumn[] = [
  {
    id: 'new',
    label: 'New',
    color: 'blue',
    candidates: [applications[4]],
  },
  {
    id: 'screening',
    label: 'Screening',
    color: 'purple',
    candidates: [applications[1]],
  },
  {
    id: 'phone_screen',
    label: 'Phone Screen',
    color: 'cyan',
    candidates: [applications[2]],
  },
  {
    id: 'technical',
    label: 'Technical',
    color: 'amber',
    candidates: [applications[0]],
  },
  {
    id: 'onsite',
    label: 'Onsite',
    color: 'orange',
    candidates: [],
  },
  {
    id: 'offer',
    label: 'Offer',
    color: 'emerald',
    candidates: [applications[3]],
  },
]

export const analytics: Analytics = {
  totalJobs: 12,
  totalApplicants: 1483,
  hiredThisMonth: 7,
  avgTimeToHire: 28,
  offerAcceptRate: 84,
  qualityOfHire: 4.3,
  costPerHire: 3200,
  sourcingChannels: [
    { name: 'Calibr', applicants: 680, hired: 4, percentage: 46 },
    { name: 'LinkedIn', applicants: 380, hired: 2, percentage: 26 },
    { name: 'Referrals', applicants: 210, hired: 1, percentage: 14 },
    { name: 'Direct', applicants: 130, hired: 0, percentage: 9 },
    { name: 'Other', applicants: 83, hired: 0, percentage: 5 },
  ],
  hiringFunnel: [
    { stage: 'Applied', count: 1483, percentage: 100, dropoff: 0 },
    { stage: 'Screened', count: 412, percentage: 28, dropoff: 72 },
    { stage: 'Phone Screen', count: 186, percentage: 13, dropoff: 55 },
    { stage: 'Technical', count: 89, percentage: 6, dropoff: 52 },
    { stage: 'Onsite', count: 34, percentage: 2.3, dropoff: 62 },
    { stage: 'Offer', count: 12, percentage: 0.8, dropoff: 65 },
    { stage: 'Hired', count: 7, percentage: 0.47, dropoff: 42 },
  ],
  weeklyApplications: [
    { week: 'Mar 31', applications: 124, interviews: 18, offers: 2 },
    { week: 'Apr 7', applications: 156, interviews: 22, offers: 3 },
    { week: 'Apr 14', applications: 198, interviews: 31, offers: 3 },
    { week: 'Apr 21', applications: 287, interviews: 44, offers: 5 },
    { week: 'Apr 28', applications: 342, interviews: 56, offers: 7 },
  ],
  diversityMetrics: {
    gender: { Male: 48, Female: 44, 'Non-binary': 5, 'Prefer not to say': 3 },
    ethnicity: { Asian: 32, White: 40, Hispanic: 14, Black: 10, Other: 4 },
    ageGroup: { '18-25': 12, '26-35': 48, '36-45': 30, '45+': 10 },
  },
}

export const conversations: Conversation[] = [
  {
    id: 'conv1',
    participantId: 'can1',
    participantName: 'Alex Chen',
    participantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    participantRole: 'Senior Frontend Engineer',
    lastMessage: 'Thanks for the quick response! I\'m very excited about the opportunity.',
    lastMessageTime: '2025-04-28T14:30:00Z',
    unread: 2,
    jobTitle: 'Senior Frontend Engineer',
    messages: [
      {
        id: 'm1',
        senderId: 'company',
        receiverId: 'can1',
        content: 'Hi Alex! We reviewed your application and were impressed by your background. Would you be available for a quick intro call this week?',
        timestamp: '2025-04-27T10:00:00Z',
        read: true,
        type: 'text',
      },
      {
        id: 'm2',
        senderId: 'can1',
        receiverId: 'company',
        content: 'Thanks for the quick response! I\'m very excited about the opportunity.',
        timestamp: '2025-04-28T14:30:00Z',
        read: false,
        type: 'text',
      },
    ],
  },
  {
    id: 'conv2',
    participantId: 'can3',
    participantName: 'Marcus Johnson',
    participantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    participantRole: 'Staff Software Engineer',
    lastMessage: 'I\'ll review the offer details and get back to you by Thursday.',
    lastMessageTime: '2025-04-27T16:45:00Z',
    unread: 0,
    jobTitle: 'Staff Software Engineer',
    messages: [
      {
        id: 'm3',
        senderId: 'company',
        receiverId: 'can3',
        content: 'Congratulations Marcus! We\'d like to extend an offer. When can we connect to walk through the details?',
        timestamp: '2025-04-27T15:00:00Z',
        read: true,
        type: 'text',
      },
      {
        id: 'm4',
        senderId: 'can3',
        receiverId: 'company',
        content: 'I\'ll review the offer details and get back to you by Thursday.',
        timestamp: '2025-04-27T16:45:00Z',
        read: true,
        type: 'text',
      },
    ],
  },
]

export const pricingPlans: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    description: 'Perfect for small teams making their first hires',
    monthlyPrice: 499,
    annualPrice: 399,
    highlighted: false,
    features: [
      'Up to 5 active job postings',
      'AI candidate matching',
      'Basic pipeline management',
      'Up to 3 team members',
      'Email support',
      'Standard analytics dashboard',
      'Candidate messaging',
      '100 AI match credits/month',
    ],
    limits: {
      jobs: 5,
      teamMembers: 3,
      aiCredits: 100,
      support: 'Email',
    },
  },
  {
    id: 'growth',
    name: 'Growth',
    description: 'For growing teams that need more power',
    monthlyPrice: 2499,
    annualPrice: 1999,
    highlighted: true,
    badge: 'Most Popular',
    features: [
      'Up to 20 active job postings',
      'Advanced AI matching & ranking',
      'Full pipeline Kanban board',
      'Up to 10 team members',
      'Skills assessments & verification',
      'Bias detection reports',
      'Advanced analytics & exports',
      'Priority support',
      '500 AI match credits/month',
      'ATS integrations (Greenhouse, Lever)',
      'Candidate salary intelligence',
      'Custom interview scorecards',
    ],
    limits: {
      jobs: 20,
      teamMembers: 10,
      aiCredits: 500,
      support: 'Priority',
    },
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'For organizations with serious hiring needs',
    monthlyPrice: 7999,
    annualPrice: 6399,
    highlighted: false,
    badge: 'Best Value',
    features: [
      'Unlimited job postings',
      'Enterprise AI engine with custom training',
      'Full pipeline + automation workflows',
      'Unlimited team members',
      'Advanced skills verification lab',
      'AI bias detection & compliance reports',
      'Custom analytics & BI integrations',
      'Dedicated Customer Success Manager',
      'Unlimited AI match credits',
      'All ATS integrations + custom API',
      'Predictive retention scoring',
      'Diversity & inclusion benchmarking',
      'SSO / SAML & advanced security',
      'SLA: 99.9% uptime',
      'Custom onboarding & training',
    ],
    limits: {
      jobs: 'Unlimited',
      teamMembers: 'Unlimited',
      aiCredits: 'Unlimited',
      support: 'Dedicated CSM',
    },
  },
]

export const marketStats = {
  companiesHiring: 14200,
  candidatesPlaced: 87400,
  avgTimeToHire: 12,
  salaryMatch: 94,
  offerAcceptRate: 89,
  activeJobs: 42800,
}

export const testimonials = [
  {
    id: 't1',
    name: 'Sarah Mitchell',
    role: 'VP of Engineering',
    company: 'Airtable',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    quote: 'Calibr cut our time-to-hire from 52 days to 18 days. The AI matching is uncanny — the top-ranked candidates are almost always our top choices after interviews.',
    metric: '65% faster hiring',
  },
  {
    id: 't2',
    name: 'David Park',
    role: 'Head of Talent',
    company: 'Loom',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    quote: 'We\'ve tried every platform out there. Calibr is in a different league. The candidate quality is exceptional and the pipeline management keeps our whole team aligned.',
    metric: '3x better candidate quality',
  },
  {
    id: 't3',
    name: 'Aisha Thompson',
    role: 'Software Engineer',
    company: 'Applied via Calibr',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aisha',
    quote: 'For the first time, I felt like I understood exactly where I stood in the process. I got matched to roles that actually fit my skills, and landed a 40% salary increase.',
    metric: '40% salary increase',
  },
  {
    id: 't4',
    name: 'Carlos Rodriguez',
    role: 'Director of People Ops',
    company: 'Retool',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=carlos',
    quote: 'The bias detection feature alone is worth the price. We\'ve seen real improvements in diversity at every stage of our pipeline since switching to Calibr.',
    metric: '28% more diverse hires',
  },
]
